services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python:/app
      - backend_media:/app/uploads
      - backend_static:/app/logs

  worker:
    volumes:
      - ./backend-python:/app
      - backend_media:/app/uploads
      - backend_static:/app/logs

  scheduler:
    volumes:
      - ./backend-python:/app

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  cv-builder:
    profiles: ["cv-builder"]
    ports:
      - "3050:3000"

  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"
